[package]
name = "comp"
version = "0.1.0"
edition = "2021"

[dependencies]
# т.к. это отдельный крейт comp, эти зависимости не нужно
# делать опциональными, они всегда нужны при компиляции
# крейта comp
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"